pull_request_rules:
  - name: Automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - status-success=Travis CI - Pull Request
    actions:
      comment:
        message: '@dependabot merge'
  - name: Automatic merge on approval
    conditions:
      - approved-reviews-by=arhix
    actions:
      merge:
        method: merge
